#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("uControlAndroid.Resource", IsApplication=true)]

namespace uControlAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::uControlAndroid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::uControlAndroid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrowLeft = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arrowRight = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int backgnd = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int backgroundBrake_fill = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int backgroundRun_fill = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int button_primary_selector = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int calibrateActive = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int CalibrateButton = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int calibrateScale = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int calibrateScaleActiveLine = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int calibrateUnselected = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int connectButton = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int EditTextStyle = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int greenStatus = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ProgressBrake = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int progressBrake_fill = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ProgressRun = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int progressRun_fill = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int redStatus = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int SeekProgressRun = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int setupActive = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int setupUnselected = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int slider1 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int slider2 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int themeActive = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int themeUnselected = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int thumb = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int touchRoom = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int wheelActive = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int wheelUnselected = 2130837533;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000c
			public const int Button01 = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int Button02 = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int Button03 = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int Button04 = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int LinearLayout01 = 2131099662;
			
			// aapt resource value: 0x7f06000b
			public const int LinearLayout02 = 2131099659;
			
			// aapt resource value: 0x7f060008
			public const int connectButton = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int editIpText = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int linearLayout1 = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int openCustomBtn = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int openSetupBtn = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int openWheelBtn = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int rl = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int seekBarBrake = 2131099657;
			
			// aapt resource value: 0x7f060011
			public const int seekBarRun = 2131099665;
			
			// aapt resource value: 0x7f060001
			public const int space1 = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int space2 = 2131099651;
			
			// aapt resource value: 0x7f06000a
			public const int wrapper = 2131099658;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int SetupLayout = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int WheelLayout = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
